#!/usr/bin/env python3
"""
generate_training_data.py

Generates synthetic wind turbine SCADA sensor data for 5 turbines over 30 days
at 10-minute intervals.

Columns:
  timestamp, turbine_id, wind_speed, rpm, gearbox_temp, bearing_vibration,
  power_output, ambient_temp, is_fault

Fault Injection:
  Turbine 3 experiences an accelerating mechanical degradation starting at 75%
  through the timeline:
    - bearing_vibration rises non-linearly
    - gearbox_temp rises non-linearly
    - power_output degrades smoothly
"""

import os
import numpy as np
import pandas as pd
from datetime import datetime, timedelta

def generate_scada_data():
    # 1. Reproducibility
    SEED = 42
    np.random.seed(SEED)

    # 2. Configuration parameters
    NUM_TURBINES = 5
    DAYS = 30
    INTERVAL_MINUTES = 10
    STEPS_PER_DAY = (24 * 60) // INTERVAL_MINUTES  # 144 steps/day
    TOTAL_STEPS = DAYS * STEPS_PER_DAY             # 4320 steps
    START_TIME = datetime(2026, 1, 1, 0, 0, 0)
    
    # Turbine specifications
    CUT_IN_WIND = 3.0    # m/s
    RATED_WIND = 12.0   # m/s
    CUT_OUT_WIND = 25.0  # m/s
    RATED_POWER = 2000.0 # kW (2 MW turbine)
    RATED_RPM = 16.0     # RPM

    # Fault window for Turbine 3: starts at 75% through the timeline
    FAULT_TURBINE_ID = 3
    FAULT_START_STEP = int(TOTAL_STEPS * 0.75)  # step 3240 (day 22.5)

    records = []

    # Generate shared weather background (with turbine-specific micro-variations)
    time_indices = np.arange(TOTAL_STEPS)
    hours = (time_indices * INTERVAL_MINUTES / 60.0) % 24.0

    # Macro ambient temperature: daily cycle (14°C min early morning, 22°C max late afternoon)
    macro_ambient = 18.0 + 4.0 * np.sin(2 * np.pi * (hours - 9.0) / 24.0)

    # Macro wind speed: diurnal cycle with peak late afternoon + synoptic weather waves
    synoptic_wave = 2.0 * np.sin(2 * np.pi * time_indices / (STEPS_PER_DAY * 5))  # 5-day weather front
    diurnal_wind = 1.5 * np.sin(2 * np.pi * (hours - 14.0) / 24.0)
    macro_wind_base = 8.5 + synoptic_wave + diurnal_wind

    for turbine_id in range(1, NUM_TURBINES + 1):
        # Turbine-specific micro-climate variation
        turbine_seed_offset = turbine_id * 100
        rng = np.random.default_rng(SEED + turbine_seed_offset)

        # 1. Ambient Temp (°C)
        ambient_noise = rng.normal(0, 0.4, TOTAL_STEPS)
        ambient_temp = np.round(macro_ambient + rng.uniform(-0.5, 0.5) + ambient_noise, 2)

        # 2. Wind Speed (m/s)
        # Add correlated noise to simulate realistic gust dynamics
        wind_noise = rng.normal(0, 1.2, TOTAL_STEPS)
        raw_wind = macro_wind_base + rng.uniform(-0.4, 0.4) + wind_noise
        wind_speed = np.clip(raw_wind, 0.5, 24.5)
        wind_speed = np.round(wind_speed, 2)

        # 3. RPM & Power Output (correlated with wind speed)
        rpm = np.zeros(TOTAL_STEPS)
        power_output = np.zeros(TOTAL_STEPS)

        for i in range(TOTAL_STEPS):
            ws = wind_speed[i]
            if ws < CUT_IN_WIND or ws >= CUT_OUT_WIND:
                # Below cut-in or above cut-out
                rpm[i] = max(0.0, rng.normal(0.5, 0.1)) if ws < CUT_IN_WIND else 0.0
                power_output[i] = 0.0
            elif CUT_IN_WIND <= ws < RATED_WIND:
                # Region II: aerodynamic ramping
                fraction = (ws - CUT_IN_WIND) / (RATED_WIND - CUT_IN_WIND)
                rpm_val = 6.0 + fraction * (RATED_RPM - 6.0) + rng.normal(0, 0.15)
                rpm[i] = np.clip(rpm_val, 5.0, RATED_RPM)
                
                # Power roughly proportional to wind_speed cubed
                cubic_fraction = ((ws - CUT_IN_WIND) / (RATED_WIND - CUT_IN_WIND)) ** 3
                power_val = cubic_fraction * RATED_POWER + rng.normal(0, 15.0)
                power_output[i] = np.clip(power_val, 0.0, RATED_POWER)
            else:
                # Region III: rated operating region (12 m/s <= ws < 25 m/s)
                rpm_val = RATED_RPM + rng.normal(0, 0.12)
                rpm[i] = np.clip(rpm_val, 15.5, 16.5)
                power_val = RATED_POWER + rng.normal(0, 10.0)
                power_output[i] = np.clip(power_val, 1950.0, 2020.0)

        rpm = np.round(rpm, 2)
        power_output = np.round(power_output, 2)

        # 4. Gearbox Temperature (°C): ambient baseline + heat generated by load (power output)
        # Normal range ~50°C to ~72°C
        load_fraction = power_output / RATED_POWER
        gearbox_base = ambient_temp + 28.0 + 26.0 * load_fraction + rng.normal(0, 0.6, TOTAL_STEPS)
        gearbox_temp = np.round(gearbox_base, 2)

        # 5. Bearing Vibration (mm/s): stable baseline with small noise
        # Normal baseline ~1.1 to 1.4 mm/s
        vib_base = 1.15 + 0.15 * load_fraction + rng.normal(0, 0.05, TOTAL_STEPS)
        bearing_vibration = np.round(np.clip(vib_base, 0.6, 2.0), 3)

        # 6. Fault Status
        is_fault = np.zeros(TOTAL_STEPS, dtype=int)

        # 7. Fault Injection for Turbine 3 (starts at step 3240, 75% through timeline)
        if turbine_id == FAULT_TURBINE_ID:
            fault_indices = np.arange(FAULT_START_STEP, TOTAL_STEPS)
            is_fault[fault_indices] = 1

            # Non-linear accelerating severity curve: progress ** 2.2
            # Starts subtle: severity at 10% progress is (0.1)^2.2 ~ 0.006
            # Ramps up aggressively towards the end
            progress = (fault_indices - FAULT_START_STEP) / float(TOTAL_STEPS - FAULT_START_STEP)
            severity = np.power(progress, 2.2)

            # Vibration rises smoothly and severely (+0 mm/s up to +5.2 mm/s)
            vibration_spike = 5.2 * severity + rng.normal(0, 0.08, len(fault_indices)) * severity
            bearing_vibration[fault_indices] = np.round(bearing_vibration[fault_indices] + vibration_spike, 3)

            # Gearbox temperature rises smoothly due to mechanical wear and friction (+0°C up to +28°C)
            temp_spike = 28.0 * severity + rng.normal(0, 0.4, len(fault_indices)) * severity
            gearbox_temp[fault_indices] = np.round(gearbox_temp[fault_indices] + temp_spike, 2)

            # Power output falls smoothly due to mechanical drag / loss of drivetrain efficiency (-0% to -38%)
            power_reduction = 1.0 - (0.38 * severity)
            power_output[fault_indices] = np.round(np.maximum(0.0, power_output[fault_indices] * power_reduction), 2)

        # Append rows for this turbine
        for step in range(TOTAL_STEPS):
            timestamp = START_TIME + timedelta(minutes=INTERVAL_MINUTES * step)
            records.append({
                "timestamp": timestamp.strftime("%Y-%m-%d %H:%M:%S"),
                "turbine_id": turbine_id,
                "wind_speed": wind_speed[step],
                "rpm": rpm[step],
                "gearbox_temp": gearbox_temp[step],
                "bearing_vibration": bearing_vibration[step],
                "power_output": power_output[step],
                "ambient_temp": ambient_temp[step],
                "is_fault": int(is_fault[step])
            })

    # Convert to DataFrame
    df = pd.DataFrame(records)

    # Save output to backend/data/training_dataset.csv
    output_dir = os.path.join(os.path.dirname(__file__), "data")
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, "training_dataset.csv")
    df.to_csv(output_path, index=False)
    print(f"[✓] Successfully generated dataset with {len(df):,} rows.")
    print(f"[✓] Saved to: {output_path}\n")

    # Print summary statistics comparing normal turbine vs turbine 3 before and during fault
    print_summary_statistics(df, FAULT_TURBINE_ID, FAULT_START_STEP)

    return df


def print_summary_statistics(df, fault_turbine_id, fault_start_step):
    print("=" * 88)
    print(" " * 26 + "SCADA SENSOR SUMMARY STATISTICS")
    print("=" * 88)

    # Normal turbines: e.g. Turbine 1 (or all normal turbines 1, 2, 4, 5)
    df_normal_t1 = df[df["turbine_id"] == 1]
    
    # Turbine 3 before fault window (first 75% steps)
    df_t3 = df[df["turbine_id"] == fault_turbine_id].reset_index(drop=True)
    df_t3_before = df_t3.iloc[:fault_start_step]
    
    # Turbine 3 during fault window (last 25% steps)
    df_t3_during = df_t3.iloc[fault_start_step:]

    # Also calculate other normal turbines average during the same late window for direct comparison
    df_others_late = df[(df["turbine_id"] != fault_turbine_id)].groupby("turbine_id").apply(
        lambda g: g.iloc[fault_start_step:], include_groups=False
    ).reset_index(drop=True)

    sensor_cols = ["bearing_vibration", "gearbox_temp", "power_output", "rpm", "wind_speed"]
    units = {
        "bearing_vibration": "mm/s",
        "gearbox_temp": "°C",
        "power_output": "kW",
        "rpm": "RPM",
        "wind_speed": "m/s"
    }

    groups = [
        ("Turbine 1 (Normal Control - All 30 Days)", df_normal_t1),
        ("Other Turbines 1,2,4,5 (Days 22.5 - 30)", df_others_late),
        ("Turbine 3 (BEFORE Fault: Days 0 - 22.5)", df_t3_before),
        ("Turbine 3 (DURING Fault: Days 22.5 - 30)", df_t3_during),
    ]

    header_fmt = "{:<42} | {:>10} | {:>10} | {:>10} | {:>10}"
    row_fmt    = "  • {:<38} | {:>10.2f} | {:>10.2f} | {:>10.2f} | {:>10.2f}"

    for col in sensor_cols:
        col_title = f"Sensor: {col} ({units.get(col, '')})"
        print(f"\n{col_title.upper()}")
        print("-" * 88)
        print(header_fmt.format("Group Segment", "Mean", "Std", "Min", "Max"))
        print("-" * 88)
        for label, grp in groups:
            s = grp[col]
            print(row_fmt.format(label, s.mean(), s.std(), s.min(), s.max()))

    print("\n" + "=" * 88)
    print("FAULT PATTERN VERIFICATION ANALYSIS")
    print("=" * 88)
    t3_pre_vib = df_t3_before["bearing_vibration"].mean()
    t3_dur_vib = df_t3_during["bearing_vibration"].mean()
    t3_dur_vib_max = df_t3_during["bearing_vibration"].max()
    vib_change = ((t3_dur_vib - t3_pre_vib) / t3_pre_vib) * 100

    t3_pre_temp = df_t3_before["gearbox_temp"].mean()
    t3_dur_temp = df_t3_during["gearbox_temp"].mean()
    t3_dur_temp_max = df_t3_during["gearbox_temp"].max()
    temp_change = ((t3_dur_temp - t3_pre_temp) / t3_pre_temp) * 100

    t3_pre_pwr = df_t3_before["power_output"].mean()
    t3_dur_pwr = df_t3_during["power_output"].mean()
    pwr_change = ((t3_dur_pwr - t3_pre_pwr) / t3_pre_pwr) * 100

    print(f"1. Bearing Vibration:")
    print(f"   - Turbine 3 Pre-fault Mean : {t3_pre_vib:.3f} mm/s")
    print(f"   - Turbine 3 Fault Window   : {t3_dur_vib:.3f} mm/s (Peak: {t3_dur_vib_max:.3f} mm/s)")
    print(f"   - Relative Shift           : +{vib_change:.1f}% increase (Clear Smooth Surge)")

    print(f"\n2. Gearbox Temperature:")
    print(f"   - Turbine 3 Pre-fault Mean : {t3_pre_temp:.2f} °C")
    print(f"   - Turbine 3 Fault Window   : {t3_dur_temp:.2f} °C (Peak: {t3_dur_temp_max:.2f} °C)")
    print(f"   - Relative Shift           : +{temp_change:.1f}% increase (Overheating Drivetrain)")

    print(f"\n3. Power Output:")
    print(f"   - Turbine 3 Pre-fault Mean : {t3_pre_pwr:.2f} kW")
    print(f"   - Turbine 3 Fault Window   : {t3_dur_pwr:.2f} kW")
    print(f"   - Relative Shift           : {pwr_change:.1f}% reduction (Efficiency Loss)")

    print(f"\n4. Fault Ground Truth Column (is_fault):")
    fault_count = df['is_fault'].sum()
    expected_faults = len(df_t3_during)
    print(f"   - Total Fault Rows: {fault_count} / {len(df)} rows ({fault_count/len(df)*100:.1f}%)")
    print(f"   - Exactly matches Turbine 3 fault window: {fault_count == expected_faults}")
    print("=" * 88 + "\n")


if __name__ == "__main__":
    generate_scada_data()
